columns:
  longitude: float
  latitude: float
  housing_median_age: float
  total_rooms: float
  total_bedrooms: float
  population: float
  households: float
  median_income: float
  median_house_value: float
  ocean_proximity: category

numerical_columns:
 - longitude
 - latitude
 - housing_median_age
 - total_rooms
 - total_bedrooms
 - population
 - households
 - median_income
 - median_house_value
 - ocean_proximity

categorical_colums:
- ocean_proximity

target_column: median_house_value

domain_value:
  ocean_proximity:
    - <1H OCEAN
    - INLAND
    - ISLAND
    - NEAR BAY
    - NEAR OCEAN

C:\Users\Admin\ML_Project1\Machine_learning_-project\housing\artifact\data_ingestion\2022-07-02-13-52-43\ingested_data\test
C:\Users\Admin\ML_Project1\Machine_learning_-project\housing\artifact\data_ingestion\2022-07-03-11-56-26\ingested_data\test